<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Letter extends Model implements HasMedia
{
    use InteractsWithMedia;

    protected $fillable = [
        'slug',
        'category',
    ];

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Letter $letter) {
            $letter->slug = Str::uuid()->toString();
            $letter->category = Str::slug($letter->category);
        });

        static::updating(function (Letter $letter) {
            $letter->category = Str::slug($letter->category);
        });
    }
}
