<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class LetterTemplate extends Model implements HasMedia
{
    use InteractsWithMedia;

    protected $fillable = [
        'slug',
        'name',
        'email',
        'date',
    ];


    protected function casts(): array
    {
        return [
            'date' => 'date'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (LetterTemplate $letterTemplate) {
            $letterTemplate->slug = Str::uuid()->toString();
        });
    }
}
